### ISSUE TITLE
updater needs improvement

### ISSUE THREAD

**Issue by tidegu** [matlab2tikz/matlab2tikz#172]
Just downloaded the latest release from here but when I run it, it says new version available! (0.3.1). I assume it's an async problem of github and file exchange, and I allowed updater to update (Although I assume github should be always the latest version, ain't I right?)

The updater updated files:
> *** Would you like matlab2tikz to self-upgrade? y/n [n]:y
> *** Downloading and unzipping to *[some_folder]*/Library Matlab/../...`parent folder?`
> *** done.

However, all the three files are in folder (which also a path in Matlab that I put almost every extensions):
> *[some_folder]*/Library Matlab/

The downloaded files are "random" for me. It includes the following unwanted files:
> ./AUTHORS
> ./ChangeLog
> ./helpers
> ./helpers/figure2dot.m
> ./helpers/pointReduction2d.m
> ./license.txt
> ./README.md
> ./THANKS
> ./version-0.3.1

Questions are:

1. Do I actually need the two files in `helpers` folder? I couldn't find any use of them in `matlab2tikz.m` and `matlab2tikzInputParser.m`.

2. I don't know how other people install the library, however I assume there might be many people like me are more happy to maintain minimum files and centralise them in somewhere. By the default updater, those files are not updated, instead, created lots of "random" files in the parent folder.

3. I'd prefer if updater doesn't stops me from converting plot into tikz file. Instead, I would like to suggest that the converting just gone through and give a warning at the end to notify users to update. In another word, `updater.m` called within `matlab2tikz.m` is for detecting new versions and gives notification, user can call `updater.m` alone to update the library.

4. I would also like to suggest updater.m detects the existence of files before being updated, and only update the existing files in proper folder. i.e., keep a very simple searching algorithm to find where these library files are, verifies if they are the right file (in order to prevent a false search and override other library files), and update only these file exists.

**Comment by egeerardyn** [comment]
Since #511 (and some extra experiments) have proven that `rehash` cannot reload live functions, we can forget about automatic updates. The only slightly more convenient thing we could do, is to (automatically or manually) update after conversion has taken place suggested in the first post.

As it stands, we have the choice:
* leave as-is (and close this issue)
* put the updater code at the end of `m2t` (and maybe even auto-update in that case).

If there is no concensus within 2 weeks, I'd vote to close this issue: we have options to disable the updater for people wanting to run m2t unattended, the choice between attended upgrade before or after conversion seems only a small difference, and moreover, an automatic upgrade might be hard to get 100% right and has the risk of screwing up our users' install.

**Comment by nschloe** [comment]
Agreed.

The thing we and the MATLAB community really need is a market place with a proper installer. I don't understand why the MathWorks hasn't put out one yet in all these years.

**Comment by okomarov** [comment]
Leave as is (and close).
