### ISSUE TITLE
R2014b: implement annotations

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#384]
Many annotations work in MATLAB <R2014a, but not yet in R2014b. This should be fixed.

**Comment by okomarov** [comment]
I started working on the annotations but to my disappointment composite annotations like e.g. `matlab.graphics.shape.TextArrow` cannot be handled by the existing functions `drawTextarrow` which will need to be expanded in order to be able to deal with HG2. 

I will push sometime a work-in-progress PR to get some feedback.

**Comment by PeterPablo** [comment]
Thanks -- this is probably one of the largest missing pieces concerning HG2 support. May be while working on it you also hit #378, which is a textbox with 3D coordinates.

**Comment by okomarov** [comment]
Main framework implemented. Todo in #549. Closing
