### ISSUE TITLE
matlab2tikz "toolbox", MLTBX files

### ISSUE THREAD

**Issue by nschloe** [matlab2tikz/matlab2tikz#421]
I received the below email from John Kelly, MathWorks, suggesting to add an MLTBX file to our repository. This somehow turns matlab2tikz into a "toolbox" which incorporates versioning and such things. I have no idea what advantages this might have.
I played around with this and found that the MLTBX file generated for a specific commit of m2t is a binary blob, and I'm really reluctant of adding this to the repository. On the other hand, of course, we would like to make life easier for anyone who wants to use matlab2tikz.

Does anyone have experience with the MLTBX mechanisms? Opinions?

> Dear File Exchange Author,
>
> As an author of a popular File Exchange submission, we would like to encourage you to offer your 
> content as a Toolbox (.mltbx file), in addition to a ZIP archive.
>
> Toolboxes are an easy way to share reusable code and provide for an enhanced user experience by 
> easily installing in MATLAB R2014b and higher. In addition, toolboxes offer an easy way to include 
> examples, help, and documentation into your submission. The R2014b release is now available for 
> download.
>
> Allowing other members of the MATLAB Community to download your submissions as a toolbox is 
> easy. Simply edit your submission, select the ‘This submission is a Toolbox’ checkbox, and then 
> republish your file. There is no need to resubmit your code.
>
>
> If you have submitted files using GitHub, you’ll need to install R2014b MATLAB, use the Package a 
> toolbox UI, and then submit the generated toolbox to your GitHub repository. The File Exchange will 
> detect the new toolbox and link to it automatically.
>
>
> If you already have R2014b and would like to submit your code as a toolbox to the File Exchange, 
> we will extract your files and make them available to users as a Zip archive.  This will ensure that all 
> MATLAB users can use your code.
>
> If you have any questions about updating your submission, please contact me. 
>
> John Kelly
> MATLAB Central Administrator
> MathWorks
> www.mathworks.com

>  In order to package your source code into a .mltbx toolbox you first need to have MATLAB version 
> 2014b installed. With 2014b running you can find the ‘Package a Toolbox’ command located in the 
> Add-ons menu which is in the Resources section of the toolstrip.

**Comment by egeerardyn** [comment]
To clearly rehash our requirements for this to be viable:
 - we need an automated mechanism to generate MLTBX files (instead of GUIs),
 - MLTBX files should not be stored in the repository to avoid blowing up the repository size,
 - the MLTBX file should be made available on FileExchange.

As it currently stands, the latter two requirements are conflicting. 
We cannot simply put the MLTBX file in the `master` branch as it blow up repository size, but that is what FileExchange expects.

The ideal solution would be if we can make "GitHub releases" ZIP files available on FileExchange. There we can add such binary MLTBX blobs without bloating the repository. Moreover, we can then just add the generating files in the repository (e.g. PRJ file contained in the MLTBX container) and maybe a script to generate the MLTBX file during the release process.
