### ISSUE TITLE
move `cleanbefore` from option to file

### ISSUE THREAD

**Issue by nschloe** [matlab2tikz/matlab2tikz#470]
This looks like an option that should be removed; after all, all it does is call one function. Instead of mingling this with the test code, it should outsourced to its own routine and explicitly called by the user. This makes clear what happens.
I bumped into this just now when the acidtests destroyed my previous test output. (Classically, destructive options should be default `false`.)

**Comment by PeterPablo** [comment]
PR #485 remove(s/d) the call to `cleanFiles()` when executing the tests. This should be reintroduced to avoid problems.

**Comment by egeerardyn** [comment]
@PeterPablo In principle I agree, but what I currently have in mind is some kind of wrapper tool around all the test facilities. I envision a workflow from the MATLAB REPL like:

```matlab
m2tdo make distclean
m2tdo test graphical
m2tdo make pdf
% and other commands
```

I think we also need a command (in such a tool) to do everything (i.e. changing directory, cleaning, running, compiling) in a single step, but I haven't converged on a particular syntax. Your opinion is, as always, very welcome on this!

However, I think that the point that @nschloe originally made, i.e. don't mix concerns in the tester, should be respected. So the cleaning should be callable independently and NOT integrated into the testing code itself. IMHO, ideally the testing code should get hidden away and regular access should occur through `m2tdo`.

**Comment by PeterPablo** [comment]
@egeerardyn, I just reread the whole issue with the different points of view. 

Personally I am against introducing yet more function calls one has to remember/look up, also in respect to keeping the hurdle low for new contributors. I acknowledge both the fact that old files from a previous test run likely obfuscate the real result, but on the other hand might come in handy for some special analysis needs (as @nschloe pointed out).

What about `testGraphical(...)`, where `...` are pairs of settings like `distclean`, `make` that take `(true|false)`?

One might take this even one step further and unite `testGraphical` and `testHeadless` (again) by introducing yet another option `type` that takes `(headless|graphical)` and only expose a **single** function `testMatlab2tikz()`, as is the case before PR #485.

**Comment by egeerardyn** [comment]
`testGraphical` etc. with extra options to do the cleaning is basically what should be removed according to this PR.

Joining the functionality of `testGraphical` and `testHeadless` was mainly what caused #485 to take so long: that was my initial implementation: just add a flag and complicate their innards. But this was met (rightly so) with resistance. In general, I think our flags are already complex enough and especially binary flags are something that we should be able to do better.

I see the `m2tdo` that I propose as the single point of access for all testing purposes (instead of `testGraphical` and `testHeadless`). So a new developer would only need to call `m2tdo run headless` or `m2tdo run graphical` and everything else (directory changing, cleaning, ...) is handled automatically. So it would be a very lightweight build tool, if you want.
That thing separates, IMHO, the different concerns more clearly and yet provides a single point of access and easy access to some common commands without complicated logic.

**Comment by PeterPablo** [comment]
When you put it that way it sounds very appealing. So we add another layer to obfuscate the magic happing inside by exposing a single wrapper. :+1:

**Comment by egeerardyn** [comment]
Let's continue this discussion in #575 . `cleanBefore` has been removed by now, but the directory changing should be moved into the `m2tdo` tool instead.
