### ISSUE TITLE
Transform LineWidth to TikZ equivalent

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#492]
Currently `getLineOptions()` ignores the width of a line as long as `strict mode` is not enabled. Wouldn't it make sense to match the linewidths to the ones known by PGFplots / TikZ, e.g `ultrathin`, `thick`, etc.?
**Literature:** 
* pgfplots.pdf -> 4.7.4 Font Size and Line Width
* pgfmanual.pdf -> 15.3.1 Graphic Parameters: Line Width, Line Cap, and Line Join

**Comment by egeerardyn** [comment]
@matlab2tikz/developers Could somebody weigh in on translating line widths (e.g. `3pt`) to their TikZ semantical counterparts (e.g. `thick`, `ultrathin`, ...)?
Personally, I'd leave this implementation as-is since I think we can get more wrong with such a mapping than we can add in value. 
If there is no demand for this feature, maybe we should close this issue?

**Comment by okomarov** [comment]
I once tried to make sense of the marker 'business' after nidrosian's initial big effort. Two days of work later, I found to my disappointment that they do not grow linearly and that my adjustments would work only for the test size. 

This feature request has all the potential to be a second marker size issue and hence I am personally for closing it :sweat_smile:

**Comment by PeterPablo** [comment]
Let's close this -- we can revive this, as soon as we run out of work :sweat_smile:
