### ISSUE TITLE
extraAxisOptions with multiple axes

### ISSUE THREAD

**Issue by pfbuxton** [matlab2tikz/matlab2tikz#670]
Hello,
It would be extremely useful if we can pass different extraAxisOptions to the different axes.
Thanks.

**Comment by PeterPablo** [comment]
It might be feasible to allow the user to fill the graphic objects tags
with arbitrary text. This way we could handle all objects in a uniform
manner (plots, subplots, legends, etc.). Opinions on that idea?

**Comment by egeerardyn** [comment]
Hi @pfbuxton, I agree that this would be useful for many people and we should indeed look into an implementation since a solution should really be feasible. In any case, this is equivalent (or extremely related) to #393, so I propose we discuss this further over there.

In #393, I also proposed a [similar approach](https://github.com/matlab2tikz/matlab2tikz/issues/393#issuecomment-61248546) as the one @PeterPablo proposed here, so perhaps that's the best way to go.

**Comment by PeterPablo** [comment]
Thanks for linking and closing here @egeerardyn. I answered from my mobile phone to give @pfbuxton a fast answer.
