### ISSUE TITLE
Light support

### ISSUE THREAD

**Issue by CsatiZoltan** [matlab2tikz/matlab2tikz#680]
It would be nice if the `light` function was supported. Up to now `I don't know how to handle this object: light` error is returned.

**Comment by egeerardyn** [comment]
I agree that it would be nice if the [`light`](http://nl.mathworks.com/help/matlab/visualize/lighting-overview.html) function (and others) of MATLAB were supported.

Unfortunately, as far as I know and was able to check, there is no support in pgfplots (1.12.1 at the time of writing) to change the lighting. I didn't check the roadmap for pgfplots, but since lighting seems to be a non-trivial task in LaTeX, I think pgfplots will not get support for it anywhere soon.

If `light` is essential to your plots, you can always submit a feature request to [`pgfplots`](https://sourceforge.net/projects/pgfplots/). But before `pgfplots` supports lighting, I don't think we can do anything substantial on our side.
The only (very minor) improvement we can carry out, is to suppress that message for `light` objects (or emit a more detailed warning and how it can be suppressed by the user) instead of the current error.

If you want to patch your `matlab2tikz` in the meanwhile, just replace
```matlab
error('matlab2tikz:handleAllChildren',                 ...
      'I don''t know how to handle this object: %s\n', ...
      get(child, 'Type'));
```
by
```matlab
warning('matlab2tikz:handleAllChildren',                 ...
       'I don''t know how to handle this object: %s\n', ...
       get(child, 'Type'));
```

**Comment by CsatiZoltan** [comment]
Ok, thanks.

**Comment by PeterPablo** [comment]
Closing, since the current status is documented in the code by 1e21354.
