### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by nivek88** [matlab2tikz/matlab2tikz#686]
Hi,

is there any setting for matlab2tikz to change the decimal separator for the axis? I would like to have a comma "," instead of the dot "." as separator. For both axis x and y.

I already used 
`'extraAxisOptions', 'x tick label style={/pgf/number format/.cd, scaled x ticks = false, set thousands separator={.}, fixed}'`
to change the thousands separator to a european format for the x axis.

I already tried `use comma` but with no success.

**Comment by egeerardyn** [comment]
There is no option in `matlab2tikz` to affect that behavior since we rely on `pgf`/`pgfplotstable` to typeset numbers.
That means that the numbers that `matlab2tikz` writes to the file, are actually independent of the formatting that is used in the end (we write `1000.3` to the output instead of a formatted version such as `1'000,3`, `1 000,3` or  `1,000.3`). 
That means you have to configure those packages to fit your preferences. I think the setting `/pgf/number format/use comma` is what you might be looking for.

More information on the actual commands can be found in section 2.7 of the [pgfplotstable](https://www.ctan.org/pkg/pgfplotstable?lang=en) manual and Section 93 of the [TikZ/pgf](https://www.ctan.org/pkg/pgf?lang=en) manual. Also the [pgfplots]((https://www.ctan.org/pkg/pgfplots?lang=en)) manual might have some pointers regarding which keys you have to set for certain parts of the graph.

**Comment by nivek88** [comment]
So, if I use

 'extraAxisOptions', 'x tick label style={/pgf/number format/.cd, scaled x ticks = false, set thousands separator={.}, fixed}',...
    'extraAxisOptions', 'y tick label style={/pgf/number format/use comma}')

the y axis uses the a comma for decimal separation. But the x axis now uses again a comma as thousand separator.
How can I set it for both axis?

**Comment by egeerardyn** [comment]
You can only supply `extraAxisOptions` once (only the last one you provide is retained), but you can provide multiple options in that option:
```
'extraAxisOptions', {'x tick label style=...', 'y tick label style=...'}
```
or 
```
'extraAxisOptions', 'x tick label style=..., y tick label style=...'
```

But please check out the manuals of `pgfplots` and `pgf` for the exact syntax of those options.

**Comment by nivek88** [comment]
The easiest way to solve this is, if you don't set any options concerning the axis into `matlab2tikz` but to set `\pgfplotsset{/pgf/number format/use comma}` into the preamble of the Latex document. So Latex will automatically transform the 1000 sep and the decimal sep.
