### ISSUE TITLE
cleanfigure on error bars lead to error when running matlab2tikz

### ISSUE THREAD

**Issue by mobiuspizza** [matlab2tikz/matlab2tikz#692]
If I run cleanfigure function on a plot with some error bars sticking outside the limits of the y-axis, then running matlab2tikz will give the following errors:

    Error using matlab2tikz>drawErrorBars (line 3817)
    Sizes of and error data not matching (6*13 ~= 98 and 6*98 ~= 13, 9*13-1 ~= 98, 9*98-1 ~= 13).

    Error in matlab2tikz>drawHggroup (line 2470)
            [m2t,str] = drawErrorBars(m2t, h);

    Error in matlab2tikz>handleAllChildren (line 654)
                [m2t, str] = drawHggroup(m2t, child);

    Error in matlab2tikz>drawAxes (line 852)
    [m2t, childrenEnvs] = handleAllChildren(m2t, handle);

    Error in matlab2tikz>saveToFile (line 450)
        m2t = drawAxes(m2t, relevantAxesHandle);

    Error in matlab2tikz (line 352)
    saveToFile(m2t, fid, fileWasOpen);

If I don't run cleanfigure first, the export runs fine.

**Comment by okomarov** [comment]
@mobiuspizza Can you please post a minimal working example that reproduces the error?

**Comment by egeerardyn** [comment]
Even without an MWE, I can indeed imagine that plots with errorbars can produce problems, since in some versions of MATLAB those are encoded in a way that will throw off `cleanfigure` (see the source code of `matlab2tikz` for the details). As far as I know, we don't account for errorbars in `cleanfigure`, which is the probably cause of this problem.

The solution would be to disable treating plots with errorbars in `cleanfigure`. I think that would make the most sense, since error bars are only useful for plots with only a few data points, such that LaTeX buffer space is not an issue).

**Comment by mobiuspizza** [comment]
Hi, I was going to post a problematic figure file but the system only accept image files, where can I upload the MWE?

**Comment by okomarov** [comment]
You can post the code that produces the problem. The simplest, i.e. stripped down of accessories, the better :)

**Comment by mobiuspizza** [comment]
Sure, here is the code:

	y = [1.0315
		0.5007
	   -0.0301
	   -0.0301
	   -0.0301
	   -0.5609
		0.7291
		0.1244
		0.1244
		0.1244
		1.0315
		0.6721
		0.4325];
	sig=[1.9583
		1.7898
		1.7087
		1.7087
		1.7087
		1.7275
		2.2662
		4.1056
		4.1056
		4.1056
		1.9583
		2.3920
		3.0602];
	figure;errorbar(1:13,y,sig,'.')
	axis([0 14 -4 4])
	cleanfigure
	matlab2tikz('temp')

**Comment by egeerardyn** [comment]
You might want to upgrade you `matlab2tikz` since I cannot reproduce the error you get.
Upon inspection of our source code, the part of the code that crashed has already been replaced by more robust code.

If you still get an error with the 1.0.0 release, please feel free to reopen this issue.
