### ISSUE TITLE
Suggestion: clip mode=individual in axis

### ISSUE THREAD

**Issue by luctrudeau** [matlab2tikz/matlab2tikz#733]
I had problems with a plot, the marks were drawn over the line. In matlab, it was ok (I change the ordering to make sure, the line was drawn last). StackExchange told me to add: "clip mode=individual" in the axis and it solve the issue.

Would it make sens to add it all the time?

**Comment by okomarov** [comment]
Hi @luctrudeau, can you please post a minimal Matlab example and the link to the SE post?

**Comment by PeterPablo** [comment]
It's [this link](http://tex.stackexchange.com/questions/10886/z-order-of-plots-pgfplots). Coincidentally I ran into the same issue yesterday and that option solved the problem for me.

I don't have a MWE at hand but basically I had a line with markers `-kx` and another line without markers `r-` crossed that line on top. The second red line correctly is displayed on top the first black line but the markers surprisingly are on the topmost layer.

**Comment by okomarov** [comment]
Upon further investigation, Matlab plots markers on top of the line. The following example illustrates this point and suggests a workaround: first plot the markers alone, and then separately the line on top of it.

However, this results in Matlab, which I assume @luctrudeau  is what you do, is not translated by `m2t` and appears to be a bug (?).
![capture](https://cloud.githubusercontent.com/assets/3731173/9309862/243b7a6e-4504-11e5-9425-db1310362764.PNG)

The code to reproduce the above:

```
t = 0:pi/20:2*pi;
subplot(211)
plot(t,sin(2*t),'-mo',...
                'LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor',[.49 1 .63],...
                'MarkerSize',10);
            
subplot(212)
plot(t,sin(2*t),'o',...
                'LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor',[.49 1 .63],...
                'MarkerSize',10);
hold on            
plot(t,sin(2*t),'-m',...
                'LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor',[.49 1 .63],...
                'MarkerSize',10);
```

**Comment by PeterPablo** [comment]
```matlab
x=0:0.03:1;
y=ones(length(x),1);

figure; clf;
h=plot(x,y,'k-*'); hold on;
set(h,'MarkerEdgeColor','g');
plot([0.5 0],[0.5 2],'r');
```

run, generate the pdf and zoom in
![image](https://cloud.githubusercontent.com/assets/4340267/9309990/4de719e6-450d-11e5-8ec8-d44c70985d8f.png)

**Comment by egeerardyn** [comment]
Well, that behavior is by design in `pgfplots`, or that's what I think at least (from the `pgfplots` manual):

> `pgfplots/clip mode=global|individual` (initially global)
This key controls how pgfplots implements the `clip=true` feature (which is on by default). Its primary motivation is control where markers are placed: are markers on top of everything else (choice `global`) or are they overdrawn by following plots (choice `individual`)?
The choice `global` tells pgfplots to install one single clip path for the complete picture. 
> In order to avoid clipped marker paths, any markers are processed after the clip path has been closed, i.e. on a separate layer (see `clip marker paths`). An unexpected side–effect is that marks are on top of plots, even if the plots have been added after the markers.
> The choice individual instructs pgfplots to install a separate clip path for every `\addplot` command. Consequently, the plot will be clipped. But most importantly, its markers will be drawn immediately after the clip path has been deactivated.
> An unexpected side–effect of `clip mode=individual` is that
>  1. the resulting pdf will be slightly larger due to the repeated paths,
>  2. custom drawing instruction like `\node` or `\draw` need to be clipped manually: use to install a custom clip path around your `\draw` instructions for such a use–case. Here, the path instruction `\pgfplotspathaxisoutline` results in a path of the axis outline, i.e. the path which is used for the background paths or for clipping. Since it is a basic level macro, it needs to be encapsulated by `\pgfextra`.

Personally, for most plots I like this default behavior where markers are plotted after everything else (but I do agree that some plots can benefit from having it the other way around).

To change this setting, there are a few things one can do:
 - set the corresponding setting globally in your LaTeX document (`\pgfplotsset{clip mode=individual}`)
 - pass this option to `matlab2tikz`, i.e. `matlab2tikz(..., 'extraAxisOptions', 'clip mode=individual')`

**Comment by cfeuersaenger** [comment]
Thanks for "ping"ing me on this item.

Believe me, I have had a hard time before I finally decided to stick 
with "clip mode=global" as default. I also think it is a reasonable 
choice, especially since it causes no surprises with older documents 
(and I am fond of backwards compatibility).

Kind regards

Christian


Am 17.08.2015 18:57, schrieb Egon Geerardyn:

**Comment by luctrudeau** [comment]
Thank you all for the quick and detailed response. The workarounds are fine with me, I just wanted to make sure you guys are informed of the issue

**Comment by okomarov** [comment]
@egeerardyn In my first figure with the two subplots (previous answer), I show that plotting the line after the markers, while producing expected results in Matlab, does not in tikz. As you pointed out, this is consistent with the `pgfplots` manual. I just want to restate, if you look at the second figure, that adding the `clip mode=individual` does **not** affect the first subplot, i.e. when I plot in Matlab at the same time both line and markers, but it does fix the inconsistent behaviour in the second subplot.

Considering that the option `clip mode=individual` is a bit obscure and that it took me a while to figure out why instead `z-order` wasn't giving me better answers, I think we should implement the default, or have a pointer (somehow) to your second solution `matlab2tikz(..., 'extraAxisOptions', 'clip mode=individual')`.

**Comment by egeerardyn** [comment]
Something we could do to inform our users about this, is checking in every axes whether such cases occur: i.e. check for every axis whether there are `line` objects with lines above line objects with markers. We can be a bit broad in this check: I wouldn't check both plots for overlap (to make sure the problem actually occurs), just that it might occur.

We could then warn the user with a `userInfo` message like:
> It seems you might have lines on top of plots with markers. Pgfplots will plot markers on top of the lines unless you specify `clip mode=individual` in `extraAxisOptions` (see #733 for more info).

As I said: in most cases I actually like that behavior, so I wouldn't change our default unless there is a majority for changing the default.

**Comment by PeterPablo** [comment]
Let me shift the majority towards @okomarov's opinion. I would also expect the code we generate to match the behavior of MATLAB, even if it is not the default behavior of pgfplots.

@egeerardyn, you might convince towards your opinion, if you can explain in more detail (MWE) when the current behavior is advantageous.

(@cfeuersaenger -- thank you for the instant response!)

**Comment by okomarov** [comment]
@egeerardyn But the user is **actively** trying to put the lines over the markers, otherwise why the double call to `plot()`? I might have not been clear, but `plot(1:10,'-rx')` with `clip mode=individual` **still** produces:
![capture](https://cloud.githubusercontent.com/assets/3731173/9335348/6aa52096-45cb-11e5-8808-554063df0f3c.PNG)

**Comment by egeerardyn** [comment]
Oh, I overlooked your point that `clip mode=individual` doesn't fix everything. Then it's a layering problem in `pgpflots`.

There might be a few workarounds, but none of which are actually nice (we can place multiple (pgfplots) `layers` or `axis` on top of each other to get the right result). Otherwise, I think we have to rely on what `pgfplots` provides.

Why I liked the current default, is because I thought that it allows the markers to overlap the axis lines. Apparently, that's not related to the `clip mode` key, but to another related key (which contains the fix to the problem we see, if I remember correctly).

The `pgfplots` manual has the following information (emphasis mine):

>  `/pgfplots/mark layer=auto|like plot|⟨layer name ⟩`   (initially `auto`)
>  An advanced key which defines the layer for plot marks. It is typically the best choice to leave it at `auto`.
> If you write `\addplot[on layer=⟨layer name⟩]`, the layer will be used for the complete plot. Plot marks are treated with special care, so you can define an own layer for plot marks.
> The initial choice auto will automatically define a “suitable” choice, leaving the responsability with pgfplots. Here, “suitable” means to respect clip mode and clip marker paths in a way such that plot marks will not be clipped even though the default layer for your plot will be clipped.
> The choice like plot will pack the marks onto the same layer as the plot they belong to. **This might cause clipped markers, i.e. markers which are only displayed partially if they are close to the boundary of the axis.**
> Finally, one can provide any ⟨layer name⟩, just as for on layer – but the layer can be different from the layer used for the plot.

I have the impression that is the workaround I used previously, since it explicitly mentions the borders.

And the bold part is the reason I'm against implementing the fix by default.

**Comment by okomarov** [comment]
I am still not following why you do not like `clip mode=individual`. From the last pic you can clearly see that markers are on top of the axis.

**Comment by egeerardyn** [comment]
@okomarov I agree. I was confusing both options. To recap: I have nothing against `clip mode=individual` (only downside is that the PDF is bigger due to many clip paths, we should test this in practice, but for many plots it should not be a problem). I do have something against `mark layer=like plot` by default, because that clips the markers at the boundary (but that one does solve the issue of Z-ordering the plots and markers, if I remember correctly).

I'm sorry for the confusion.
