### ISSUE TITLE
histogram strange legend symbol

### ISSUE THREAD

**Issue by dachziegel** [matlab2tikz/matlab2tikz#734]
When converting a histogram to tikz using matlab2tikz, the symbol in the legend is strange.

simple example:

    a = randn(10000,1); 
    hist(a);
    legend('demo');

![demo](https://cloud.githubusercontent.com/assets/6340397/9333955/884e60ca-45cc-11e5-9acb-f0c57972cd1b.png)
generated tikz code: [demo.tex](https://gist.github.com/dachziegel/ada5b0ac37a62d96fd1a#file-demo-tex)

I am using the latest development version of matlab2tikz and MATLAB R2015a on Linux.

**Comment by okomarov** [comment]
Hi @dachziegel,
The legend corresponds to a patch-type graph. This is because Matlab's `hist()` draws the histogram with `patch()` objects instead of using `barseries`. Thus, we cannot detect in this case that the plot is a bar-type. 

I suggest to use the new `histogram()` function as a workaorund.

**Comment by egeerardyn** [comment]
Thank you for reporting this, however, I think this is mostly related to "funky" behavior by `hist`, nothing strange on our side. As such, I don't intend to fix this (spent too many hours already on related issues), but luckily: there are very good workarounds!

The use of `hist` has been discouraged by The MathWorks since R2014b.
What you see here, is actually an artefact of the internal representation of those plots: those are not represented by `barseries` but by `patch`es, if I remember correctly. In general, I think the internal representation used by `hist` is a mess (it calls a legacy variant of `bar` to do the plotting, hence the problems you see). Both have a different legend icon in `pgfplots`.

The workaround consists of the second and third subplot you see below:

```matlab
a = randn(1,1000);

subplot(1,3,1);
hist(a);
legend('hist')

subplot(1,3,2);
[n,x] = hist(a)
bar(x,n,1)
legend('bar')

subplot(1,3,3)
h = histogram(a, 10)
legend('histogram')

matlab2tikz('histogram.tex','standalone',true)
```
![histogram](https://cloud.githubusercontent.com/assets/177360/9334302/762b60da-45ce-11e5-923b-ff9946231519.png)

As you can see, we do handle `histogram` better, so I would advise to use that instead since that's what TMW is recommending as well.

If you are worried about backwards compatibility: calling `bar` and `hist` yourself also does the job. Also note that `hist`/`histc` and `histogram` use slightly different algorithms to determine the bins, that's why you see slightly different plots.

**Comment by dachziegel** [comment]
thanks for the quick response. However, in my real use case I am using `ecdfhist` which uses `bar` internally; is there a known workaround for this too?

**Comment by egeerardyn** [comment]
With `bar` (instead of `hist`), it should produce decent legends as you see above, unless they call `bar(..., 'hist')`, which is how `hist` calls `bar` internally (which itself calls `barV6`).

I just had another look at `barV6`, but I cannot see any way for us to distinguish such plots from normal `patch` plots. As such: I don't believe we can provide any workarounds at that level.

However, when I read the help of `ecdfhist`, there seems to be very little actual functionality in that function. 

So I think it might be very easy to implement it again yourself. As a dirty way around it: you could just take TMW's code, replace `hist` with decent calls to `histogram` (or `bar` and `hist` together) and put the patched `ecdfhist` file in your [userpath](http://nl.mathworks.com/help/matlab/ref/userpath.html).

**Comment by dachziegel** [comment]
Thanks for all your tips, I replaced `ecdfhist` by `histogram(x, 'Normalization','pdf');` and its working fine with `matlab2tikz`.
