### ISSUE TITLE
pi in ticklabels are not exported in mathmode

### ISSUE THREAD

**Issue by murmlgrmpf** [matlab2tikz/matlab2tikz#820]
I have a plot that uses multiples of pi as yticklabels. When I export the plot using matlab2tikz, it is not putting the \pi in math mode, what causes latex to throw an error.

Fix: parse ticklabels for latex strings that need to be in math mode

**Comment by egeerardyn** [comment]
Could you please provide us with a bit of code to reproduce this problem?
Could you also tell what version of MATLAB/Octave you are using (tick labels and especially their interpeter have changed quite a bit during the last few versions).

**Comment by murmlgrmpf** [comment]
I am running on Matlab r2015b. The following code reproduces the issue:

'''
ang = linspace(0,2*2*pi,100);
amp = sin(ang);

plot(ang,amp)

ax = gca;
ax.XTick =[0, pi,2*pi, 3*pi,4*pi];
ax.XTickLabel = {'0', '\pi','2\pi','3\pi','4\pi'};

matlab2tikz('test.tex','standalone',true,...
    'parseStringsAsMath',true,'interpretTickLabelsAsTex',true);
'''

**Comment by murmlgrmpf** [comment]
leaving out the options does not seem to change the behavior.

**Comment by murmlgrmpf** [comment]
I have tinkered around with the options 'interpretTickLabelsAsTex' 'parseStrings' and 'parseStringsAsMath' but no combination fixes the issue.

**Comment by murmlgrmpf** [comment]
I have a workaround: put $\pi$ in the ticklabels fixes matlab2tikz export, but breaks the matlab plot.
Therefore I still think it would be better to fix this in matlab2tikz.

**Comment by egeerardyn** [comment]
I can confirm that this happens using the code from the `master` branch (i.e. what you get when you download from the FileExchange), however, this bug is already solved in the current `develop` branch. 

So you can either wait for the next release (may take a few weeks/months) or download the [ZIP file from our current develop branch](https://github.com/matlab2tikz/matlab2tikz/archive/develop.zip), which is quite reliable, but not as well-tested as the version you find on FileExchange.

Thank you for reporting it, anyway!
