### ISSUE TITLE
verify Octave/Matlab with Octave 4.0

### ISSUE THREAD

**Issue by sha77** [matlab2tikz/matlab2tikz#843]
Dear maintainers of matlab2tikz

Thank you for you work on matlab2tikz. I tried to use it with Octave 4.0 and 4.1
and ran into a small problem using matlab2tikz with the most recent version of Octave.

On line 6042 of matlab2tikz.m I replaced
if ~isempty(vData) % found the right environment
by
if ~isempty(vData.Name) % found the right environment

With this small change a few test with Matlab and Octave4.0 and 4.1 worked just fine. I have no idea whether there are side effecs.

With best regards

Andreas

**Comment by egeerardyn** [comment]
Hi,

Thank you for reporting this, we are aware of this and in our current development version, this has already been addressed. I don't know why Octave decided to change this behavior, but we haven't seen any side-effects in our fix.

To use the development version, please download our [`develop` branch](https://github.com/matlab2tikz/matlab2tikz/tree/develop) instead of the master branch (and the version you get from FileExchange).

If you do find other problems in Octave 4.0/4.1, please let us know.
