### ISSUE TITLE
In Octave using latest release colours are not defined properly

### ISSUE THREAD

**Issue by crobarcro** [matlab2tikz/matlab2tikz#866]
Using the latest release with Octave 4.1 I created a figure with this line in it:

`\definecolor{m}{rgb}{1.00000,0.00000,1.00000}%`

The line should have read:

`\definecolor{mycolor}{rgb}{1.00000,0.00000,1.00000}%`

I suspect there will be a bug or Matlab/Octave difference with the code in matlab2tikz function 'generateColorDefinitions' where this line is written.

In octave, I get the following:

```
octave:8> names{1} = 'mycolor1'; sprintf(['\\definecolor{%s}{rgb}{''''}%%\n'], names{1}')
ans = \definecolor{m}{rgb}{''}%
```

whereas matlab does

```
>> names{1} = 'mycolor1'; sprintf(['\\definecolor{%s}{rgb}{''''}%%\n'], names{1}')

ans =

\definecolor{mycolor1}{rgb}{''}%
```

If I remove the transpose operator from names{k} I get the expected result in Octave too. 

```
octave:9> names{1} = 'mycolor1'; sprintf(['\\definecolor{%s}{rgb}{''''}%%\n'], names{1})
ans = \definecolor{mycolor1}{rgb}{''}%
```

If this transpose operator meant to be there?

**Comment by crobarcro** [comment]
looks like an octave [bug](http://savannah.gnu.org/bugs/?47192)

This will probably be fixed in the next release.

**Comment by egeerardyn** [comment]
Thank you for reporting this issue, however, I think that in the current `develop` branch this may already be fixed. You may want to try that out in the meanwhile. In Octave 4.0, we had to work around quite a few regressions on their part, but that code hasn't made it to the `master` branch (sorry, I'm currently writing my thesis and there have been a few things that I still need to fix before I am willing to call `develop` stable enough for a real release).

Anyhow, as far as I know, Octave 4.1 has not been officially release. I don't really intend on supporting non-stable versions of either Octave or MATLAB. If final releases of either cause trouble, we can work around those issues, but it makes no sense to support the bleeding edge of Octave (since `matlab2tikz` has enough rough edges of its own that have a higher priority).

**Comment by crobarcro** [comment]
Thanks for replying, yes, I meant Octave 4.0. or at least the current stable release. However, this is an Octave regression which has already been fixed on the stable branch after I reported it earlier, so I also agree that you don't need to take any action. Eventually a new version of Octave will appear and all will be well again.

Speaking as someone who took a long time to finish their PhD thesis, thanks for being so responsive, but I agree, get on with it! :-)
