### ISSUE TITLE
matlab2tikz smudge the data points 

### ISSUE THREAD

**Issue by kristianmeyer** [matlab2tikz/matlab2tikz#911]
Hi

I have an issue that matlab2tikz 'smugde' my data. I attached a pdf-file in which the 4th subfigure has smugded data points. The real graph shown in MATLAB does not include these spikey points. 
I used cleanfigure and compiled the figure using lualatex. Is it possible to fix this? 

Thank you. 

[test-figure0.pdf](https://github.com/matlab2tikz/matlab2tikz/files/295569/test-figure0.pdf)

**Comment by miscco** [comment]
Could you please provide some more information about your issue.

1. A MWE, so we can reproduce it locally
2. The original MATLAB figure, that shows the correct image (Exported directly as jpeg)
3. Which matlab2tikz version are you using and hat is you pgfplots version (See the FAQ for that please)

**Comment by kristianmeyer** [comment]
Sorry for being so unclear. MWE:


```
\documentclass{article}
\usepackage{pgfplots}
\pgfplotsset{compat=1.13}  

\newlength\figureheight 
\newlength\figurewidth 

\begin{document}
\begin{figure}
\setlength\figureheight{5cm} 
\setlength\figurewidth{\textwidth} 
\input{Q.tex} 
\end{figure}
\end{document}
```


Correct figure from matlab:
![q](https://cloud.githubusercontent.com/assets/19709279/15747355/a4ac4984-28da-11e6-8e9b-8447acac2702.jpg)

The Q.tex file zipped:
[Q.tex.zip](https://github.com/matlab2tikz/matlab2tikz/files/295754/Q.tex.zip)

Using the newest matlab2tikz verision and pgfplots v. 1.13

This this also happens when I do not use cleanfigure.

**Comment by miscco** [comment]
@kristianmeyer Thanks for the file. Could you also provide the MALTAB code that lead to the tex file.

**Comment by kristianmeyer** [comment]
MWE.m produces the tex file
[Q.zip](https://github.com/matlab2tikz/matlab2tikz/files/295796/Q.zip)

**Comment by miscco** [comment]
@kristianmeyer Please try the recent development branch.

**Comment by miscco** [comment]
@kristianmeyer I can reproduce your issue. However, this is not a problem on the m2t side but stems from your data. You have a very densely sampled timeseries, that your are plotting, which has some delicate features. This can be seen when you zoom in in the respective areas that are corrupted in the pdf, where you will find some zig-zag patterns.

Now due to the high sampling density, the standard LineWidth of the plot leads to the "corruption", as the lines of those small zig-zags overlap. The only sensible solution that I see is to set the LineWidth of the respective plots to 0.2 or similar.  

In any case i cannot see any problem with m2t here.
