### ISSUE TITLE
3D quiver plots do not get exported correctly

### ISSUE THREAD

**Issue by RobDal** [matlab2tikz/matlab2tikz#939]
Hi everybody,

I noticed that the arrows of a quiver3 plot are not exported correctly. Their lengths are always shorter than they are supposed to be.
Example:
`scatter3([0 1],[0 1],[0 1]);
hold on;
quiver3(0,0,0,1,1,1,0);
matlab2tikz('test.tex');`
yields
![matlab](https://cloud.githubusercontent.com/assets/20945165/17548530/95ad264a-5eec-11e6-9942-f981bed018c9.JPG)
but in the exported tex file, the arrow gets just drawn to `(0.9,0.9,0.9)`:
`\addplot3 [arrow1] coordinates{(0,0,0) (0.9,0.9,0.9)};`
![tikz](https://cloud.githubusercontent.com/assets/20945165/17548617/f7bb37b4-5eec-11e6-9e51-5b66301edeec.JPG)
Often scaling the arrows in Matlab does not have any effect, either. In this small example it has. The scaling factor always seems to be the same for all arrows in one plot, but can differ in different plots.

What can I do about it?

**Comment by egeerardyn** [comment]
Thank you for reporting this so completely!

The quiver functionality is something we have worked on quite a bit lately and from a first glance, it seems that you are using the "old" version as published on the FileExchange.
In the current [development version](https://github.com/matlab2tikz/matlab2tikz/tree/develop), this issue is no longer present and produces
![issue939](https://cloud.githubusercontent.com/assets/177360/17548980/8dfaee9e-5eee-11e6-9abd-a7fff950e777.png)

You can get this version directly from GitHub (click download in the link above), but within a few weeks, it should be published on the MathWorks website as well.
