### ISSUE TITLE
Bode title and x-label

### ISSUE THREAD

**Issue by Niechos** [matlab2tikz/matlab2tikz#945]
Hi, I only just started using matlab2tikz so excuse obvious/noob questions.

Bug found when using matlab2tikz on bode plot. The final figure in my latex document has no title or x-axis label. 

in Matlab: (2015b)
```matlab
bode(random_data.mat)
%title=('blabla') tried manually overwriting the title of the bode plot to see if this would solve 
matlab2tikz('figure.tex')
```

then in latex I use:
preamble:
```latex
\usepackage{tikz}
\usepackage{pgfplots}

\usepgfplotslibrary{external}
\tikzexternalize[prefix=Tikzplots/]
\pgfplotsset{compat=newest}

%document:
\begin{figure}[h]
	\input{figure.tex}
\end{figure}
```

I found some previous issues with the bode plots
https://github.com/matlab2tikz/matlab2tikz/issues/913
https://github.com/matlab2tikz/matlab2tikz/issues/173
so if this issue is already known nevermind this post.

**Comment by Niechos** [comment]
btw, workaround is adding 
title={xxx},
xlabel={yyy},
to the texfile

**Comment by egeerardyn** [comment]
The handling of bode plots is indeed not perfect in matlab2tikz, as you indeed noticed from other reports. Thank you for bringing this to our attention again :-)

Unfortunately, the internal representation of those bode plots is something that is quite hard to disentangle and hence not simple to implement in matlab2tikz, which is why we are having a hard time with it (that, together with the fact that many of the core members have either just defended their PhD or are in the final stages of writing their PhD thesis). As such, I can't make any promises on a time frame within which we can improve this feature.

What you can try, however, is to download the [develop](https://github.com/matlab2tikz/matlab2tikz/archive/develop.zip) version (which should be almost ready to use in production) instead of the one available on FileExchange.

**Comment by egeerardyn** [comment]
Closing this as a duplicate.
